#!/bin/zsh
# Used to deploy on server

echo "\nInstalling Dependencies...\n"
cd /opt/fbsurvivor
/home/dan/.cargo/bin/uv sync --no-dev

echo "\nStopping services...\n"
sudo systemctl stop wsgi-server-fbsurvivor.service

/home/dan/.cargo/bin/uv run --no-dev python manage.py migrate
/home/dan/.cargo/bin/uv run --no-dev python manage.py collectstatic --no-input
/home/dan/.cargo/bin/uv run --no-dev python manage.py check --deploy

echo "\nStarting services...\n"
sudo systemctl start wsgi-server-fbsurvivor.service

sleep 2
