#!/usr/bin/env sh

echo "\nStopping services...\n"
ssh linode sudo systemctl stop wsgi-server-fbsurvivor.service

echo "\nStarting services...\n"
ssh linode sudo systemctl start wsgi-server-fbsurvivor.service

sleep 2
curl -X GET -I https://fbsurvivor.com
