# Generated by Django 5.0.6 on 2024-07-05 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_remove_player_has_sms_reminders_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("player_statuses", models.BinaryField()),
                ("board", models.BinaryField()),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_boards",
                        related_query_name="cached_board",
                        to="core.season",
                    ),
                ),
            ],
        ),
    ]
