# Generated by Django 5.0.6 on 2024-07-06 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_cachedboard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="league",
        ),
        migrations.DeleteModel(
            name="League",
        ),
    ]
