# Generated by Django 5.0.6 on 2024-07-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_remove_player_league_delete_league"),
    ]

    operations = [
        migrations.AlterField(
            model_name="week",
            name="lock_datetime",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="week",
            name="week_num",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pick_01", models.CharField(max_length=3, null=True)),
                ("pick_02", models.CharField(max_length=3, null=True)),
                ("pick_03", models.CharField(max_length=3, null=True)),
                ("pick_04", models.CharField(max_length=3, null=True)),
                ("pick_05", models.CharField(max_length=3, null=True)),
                ("pick_06", models.CharField(max_length=3, null=True)),
                ("pick_07", models.CharField(max_length=3, null=True)),
                ("pick_08", models.CharField(max_length=3, null=True)),
                ("pick_09", models.CharField(max_length=3, null=True)),
                ("pick_10", models.CharField(max_length=3, null=True)),
                ("pick_11", models.CharField(max_length=3, null=True)),
                ("pick_12", models.CharField(max_length=3, null=True)),
                ("pick_13", models.CharField(max_length=3, null=True)),
                ("pick_14", models.CharField(max_length=3, null=True)),
                ("pick_15", models.CharField(max_length=3, null=True)),
                ("pick_16", models.CharField(max_length=3, null=True)),
                ("pick_17", models.CharField(max_length=3, null=True)),
                ("pick_18", models.CharField(max_length=3, null=True)),
                ("result_01", models.CharField(max_length=1, null=True)),
                ("result_02", models.CharField(max_length=1, null=True)),
                ("result_03", models.CharField(max_length=1, null=True)),
                ("result_04", models.CharField(max_length=1, null=True)),
                ("result_05", models.CharField(max_length=1, null=True)),
                ("result_06", models.CharField(max_length=1, null=True)),
                ("result_07", models.CharField(max_length=1, null=True)),
                ("result_08", models.CharField(max_length=1, null=True)),
                ("result_09", models.CharField(max_length=1, null=True)),
                ("result_10", models.CharField(max_length=1, null=True)),
                ("result_11", models.CharField(max_length=1, null=True)),
                ("result_12", models.CharField(max_length=1, null=True)),
                ("result_13", models.CharField(max_length=1, null=True)),
                ("result_14", models.CharField(max_length=1, null=True)),
                ("result_15", models.CharField(max_length=1, null=True)),
                ("result_16", models.CharField(max_length=1, null=True)),
                ("result_17", models.CharField(max_length=1, null=True)),
                ("result_18", models.CharField(max_length=1, null=True)),
                (
                    "player_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.playerstatus"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.season"
                    ),
                ),
            ],
        ),
    ]
