# Generated by Django 5.0.6 on 2024-07-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_week_lock_datetime_alter_week_week_num_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="rank",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
