# Generated by Django 5.0.6 on 2024-07-06 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_board_rank"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="rank",
            new_name="ranking",
        ),
    ]
