# Generated by Django 5.0.6 on 2024-07-06 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_rename_rank_board_ranking"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CachedBoard",
        ),
    ]
