# Generated by Django 5.1.1 on 2024-09-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_emaillogrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="description",
            field=models.CharField(default="", max_length=16),
        ),
    ]
