# Generated by Django 5.1.3 on 2024-11-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_season_is_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatus",
            name="has_complete_picks",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="playerstatus",
            name="has_won_gt_buy_in",
            field=models.BooleanField(default=False),
        ),
    ]
