# Generated by Django 5.1.7 on 2025-05-12 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_playerstatus_has_complete_picks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerstatus",
            name="has_complete_picks",
        ),
        migrations.RemoveField(
            model_name="playerstatus",
            name="has_won_gt_buy_in",
        ),
    ]
