# Generated by Django 5.1.7 on 2025-05-13 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_remove_playerstatus_has_complete_picks_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_links",
                        related_query_name="magic_link",
                        to="core.player",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TokenHash",
        ),
    ]
