# Generated by Django 5.1.7 on 2025-05-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_magiclink_delete_tokenhash"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoggedOutTokens",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=1024, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
    ]
