# Generated by Django 5.1.7 on 2025-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_loggedouttokens_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatus",
            name="can_buy_back",
            field=models.BooleanField(default=True),
        ),
    ]
