# Generated by Django 5.1.7 on 2025-05-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_playerstatus_can_buy_back"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerstatus",
            name="can_buy_back",
        ),
        migrations.AddField(
            model_name="playerstatus",
            name="did_buy_back",
            field=models.BooleanField(default=False),
        ),
    ]
