# Generated by Django 5.1.7 on 2025-07-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_remove_playerstatus_can_buy_back_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatus",
            name="can_buy_back",
            field=models.BooleanField(default=True),
        ),
    ]
