name: CI

on:
  push:
    paths:
      - "fbsurvivor/**"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  check:
    name: Continuous Integration
    runs-on: ubuntu-latest
    env:
      ENV: dev
      DOMAIN: http://127.0.0.1:8000
      SECRET_KEY: abcdefghijklmnop
      PGDATABASE: ci
      PGUSER: postgres
      PGPASSWORD: password
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.10"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install ruff
        run: uv tool install ruff

      - name: Ruff Linting Check
        run: ruff check .
      - name: Ruff Imports Check
        run: ruff check --select I
      - name: Ruff Format Check
        run: ruff format --check
      - name: Run Tests
        run: pytest -p no:warnings .
